version: '3'

services:
  alpaca-lora:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "0"
    image: alpaca-lora
    shm_size: '64gb'
    volumes:
      - /home/dsc-admin/Documents/alpaca-lora:/workspace
    ports:
      - 7860:7860
    tty: true 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  alpaca-lora:
    name: alpaca-lora
